### ISSUE TITLE
Changing 'timeToDeploy' Value from Source

### ISSUE THREAD

**Issue by icpenguins** [newrelic/newrelic-azure-devops-statistics#3]
Is there a reason that a value from the source document would be converted on the New Relic side? Understandably, the Microsoft documentation ([link](https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/releaseenvironment#timetodeploy)) is a bit lacking, but it is not typically a best practice to get in the habit of changing source data. The largest issue that comes to mind is that `* 60` could "in theory" create an integer overflow ([link](https://en.wikipedia.org/wiki/Integer_overflow)). Although highly unlikely due to the size of `number` ([link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_VALUE)), it doesn't seem like a best practice and also confuses downstream users who do not know how to review the source.

https://github.com/newrelic/newrelic-azure-devops-statistics/blob/ec43a46d9190cac48e41e1b239f8c7386acfa499/AzureDevops2NewRelic/index.js#L70

I would suggest creating a new data type `timeToDeploySec` for backward compatibility and leaving the type alone.

**Comment by kidk** [comment]
The reasoning was that New Relic has specific support for timestamps, for example when showing the data in dashboards it would convert it to a date, or time passed since. 

I agree it's not ideal and have changed it in https://github.com/newrelic/newrelic-azure-devops-statistics/commit/317d584492c296ff92e24226afb7608e006623cb
